---
title: "park_geospatial_data"
author: "Katie Willi"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Produces a list of all relevant AOIs for querying water quality data portals for each park unit, as well as a 10 km radius around each park unit:

- 

```{r}
library(tidyverse)
library(sf)
library(tigris)

parks <- st_read('data/in/nps_boundary.shp') %>%
  sf::st_buffer(dist = 10000)
park_list <- unique(parks$UNIT_CODE) 
states <- tigris::states()

data<-function(parks){

    parks <- filter(parks, UNIT_CODE %in% park_list[1]) #%>% summarize()
    places <- tigris::places(state = unique(parks$STATE), filter_by = parks) %>% select(NAMELSAD, STATEFP) %>% 
      left_join(st_drop_geometry(states), by = "STATEFP") %>%
      select(NAMELSAD, STATEFP) %>% 
      mutate(TYPE = "PLACE")
    huc12 <- nhdplusTools::get_huc(AOI = parks, type = "huc12") %>% select() mutate(TYPE = "HUC12")
    zipcode <- tigris::zctas(filter_by = parks) %>% mutate(TYPE = "ZIPCODE")
    
  }
  
park_list %>%
  map_dfr(., )
  ```
  
  