---
title: "Deliverable-1-Exploring-Data"
author: "Katie Willi"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sf)
library(ggspatial)
library(ggpubr)
library(scales)
library(mapview)
library(tigris)
library(USA.state.boundaries)
library(nngeo)


load("data/alldata.RData")
map(list.files('src/', full.names = TRUE), source)

npca <- getNPCA()
no_water_parks <- read_csv("data/no_water.csv")
parks <- getParkUnits() %>%
  st_join(npca) %>%
merge(., no_water_parks, by.x = "UNIT_NAME", by.y = "Park", all.x = TRUE) %>%
  # Some official park names have changed since the last HIS update (e.g. from "Site" to "Park", capitalization differences, etc. 
  # Here I am manually capturing the parks without hydrogrphy features that the merge didn't capture:
mutate(Hydrography = ifelse(UNIT_NAME %in% c("Brown v. Board of Education National Historical Park", "Carter G. Woodson Home National Historic Site",
                                             "Harry S Truman National Historic Site", "Lewis and Clark National Historic Trail", 
                                             "Longfellow House-Washington's Headquarters National Historic Site", 
                                             "Martin Luther King, Jr., National Historical Park", "Martin Luther King, Jr., Memorial", 
                                             "Thomas Edison National Historical Park", "White House"), "None", Hydrography))

# Ugly state delineation:  
full_usa <- tigris::states()

# making the USA "pretty":
prettier <- USA.state.boundaries::state_boundaries_wgs84 %>% filter(NAME %in% c("Hawaii", "Michigan") & TYPE == "Land") %>%
  st_transform(3857)
usa <- tigris::states(resolution = "20m") %>% filter(!NAME %in% c("Michigan", "Hawaii")) %>%
  st_transform(3857) %>%
  bind_rows(prettier)
rm(prettier)

# For figures:
state_mapper <- usa %>%
  usa_mapper()
  
parks_mapper <- parks %>%
  sf::st_centroid() %>%
  st_join(st_transform(tigris::states(), 3857)) %>%
  distinct(UNIT_CODE, .keep_all = TRUE) %>%
  usa_mapper()

# Incorporate new-found info about parks without water in them, while
# preserving the original dataset
original_dataset_park <- final_dataset_park
final_dataset_park <- original_dataset_park %>%
  dplyr::left_join(as_tibble(select(parks, UNIT_CODE, Hydrography), by = "UNIT_CODE")) #%>%
  # remove parks that don't have waterbodies in them, e.g., the White House
  # filter(is.na(Hydrography))
```

Providing an example of the different assessment unit types in ATTAINS:
```{r}
nps_attains_points <- readRDS('data/00_nps_attains_point.RDS')%>% dplyr::select(c(UNIT_CODE, nhdplusid, everything(.)))
nps_attains_lines <- readRDS('data/00_nps_attains_line.RDS') %>% dplyr::select(c(UNIT_CODE, nhdplusid, everything(.))) 
nps_attains_areas <- readRDS('data/00_nps_attains_area.RDS') %>% dplyr::select(c(UNIT_CODE, nhdplusid, everything(.))) 

         cols <- c("#7C221D", "#E7331A", "#F16A16", "#FFC82F", "#0D98BA", "#0074A5", "#2E5895",
                   "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7",
                   "#1D0255", "#2B0071", "#022394", "#43B54C", "#FAEF44", "#F39E3A", "#EE2939",
                   "#CC99C9", "#9EC1CF", "#9EE09E", "#FDFD97", "#FEB144", "#FF6663",
                   "#7C221D", "#E7331A", "#F16A16", "#FFC82F", "#0D98BA", "#0074A5", "#2E5895",
                   "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7",
                   "#1D0255", "#2B0071", "#022394", "#43B54C", "#FAEF44", "#F39E3A", "#EE2939",
                   "#CC99C9", "#9EC1CF", "#9EE09E", "#FDFD97", "#FEB144", "#FF6663",
                   "#7C221D", "#E7331A", "#F16A16", "#FFC82F", "#0D98BA", "#0074A5", "#2E5895",
                   "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7",
                   "#1D0255", "#2B0071", "#022394", "#43B54C", "#FAEF44", "#F39E3A", "#EE2939",
                   "#CC99C9", "#9EC1CF", "#9EE09E", "#FDFD97", "#FEB144", "#FF6663",
                   "#7C221D", "#E7331A", "#F16A16", "#FFC82F", "#0D98BA", "#0074A5", "#2E5895",
                   "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7",
                   "#1D0255", "#2B0071", "#022394", "#43B54C", "#FAEF44", "#F39E3A", "#EE2939",
                   "#CC99C9", "#9EC1CF", "#9EE09E", "#FDFD97", "#FEB144", "#FF6663",
                   "#7C221D", "#E7331A", "#F16A16", "#FFC82F", "#0D98BA", "#0074A5", "#2E5895",
                   "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7",
                   "#1D0255", "#2B0071", "#022394", "#43B54C", "#FAEF44", "#F39E3A", "#EE2939",
                   "#CC99C9", "#9EC1CF", "#9EE09E", "#FDFD97", "#FEB144", "#FF6663",
                   "#7C221D", "#E7331A", "#F16A16", "#FFC82F", "#0D98BA", "#0074A5", "#2E5895",
                   "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7",
                   "#1D0255", "#2B0071", "#022394", "#43B54C", "#FAEF44", "#F39E3A", "#EE2939",
                   "#CC99C9", "#9EC1CF", "#9EE09E", "#FDFD97", "#FEB144", "#FF6663",
                   "#7C221D", "#E7331A", "#F16A16", "#FFC82F", "#0D98BA", "#0074A5", "#2E5895",
                   "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7",
                   "#1D0255", "#2B0071", "#022394", "#43B54C", "#FAEF44", "#F39E3A", "#EE2939",
                   "#CC99C9", "#9EC1CF", "#9EE09E", "#FDFD97", "#FEB144", "#FF6663",
                   "#7C221D", "#E7331A", "#F16A16", "#FFC82F", "#0D98BA", "#0074A5", "#2E5895",
                   "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7",
                   "#1D0255", "#2B0071", "#022394", "#43B54C", "#FAEF44", "#F39E3A", "#EE2939",
                   "#CC99C9", "#9EC1CF", "#9EE09E", "#FDFD97", "#FEB144", "#FF6663",
                   "#7C221D", "#E7331A", "#F16A16", "#FFC82F", "#0D98BA", "#0074A5", "#2E5895",
                   "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7",
                   "#1D0255", "#2B0071", "#022394", "#43B54C", "#FAEF44", "#F39E3A", "#EE2939",
                   "#CC99C9", "#9EC1CF", "#9EE09E", "#FDFD97", "#FEB144", "#FF6663",
                   "#7C221D", "#E7331A", "#F16A16", "#FFC82F", "#0D98BA", "#0074A5", "#2E5895",
                   "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7",
                   "#1D0255", "#2B0071", "#022394", "#43B54C", "#FAEF44", "#F39E3A", "#EE2939",
                   "#CC99C9", "#9EC1CF", "#9EE09E", "#FDFD97", "#FEB144", "#FF6663",
                   "#7C221D", "#E7331A", "#F16A16", "#FFC82F", "#0D98BA", "#0074A5", "#2E5895",
                   "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7",
                   "#1D0255", "#2B0071", "#022394", "#43B54C", "#FAEF44", "#F39E3A", "#EE2939",
                   "#CC99C9", "#9EC1CF", "#9EE09E", "#FDFD97", "#FEB144", "#FF6663",
                   "#7C221D", "#E7331A", "#F16A16", "#FFC82F", "#0D98BA", "#0074A5", "#2E5895",
                   "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7",
                   "#1D0255", "#2B0071", "#022394", "#43B54C", "#FAEF44", "#F39E3A", "#EE2939",
                   "#CC99C9", "#9EC1CF", "#9EE09E", "#FDFD97", "#FEB144", "#FF6663",
                   "#7C221D", "#E7331A", "#F16A16", "#FFC82F", "#0D98BA", "#0074A5", "#2E5895",
                   "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7",
                   "#1D0255", "#2B0071", "#022394", "#43B54C", "#FAEF44", "#F39E3A", "#EE2939",
                   "#CC99C9", "#9EC1CF", "#9EE09E", "#FDFD97", "#FEB144", "#FF6663",
                   "#7C221D", "#E7331A", "#F16A16", "#FFC82F", "#0D98BA", "#0074A5", "#2E5895",
                   "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7",
                   "#1D0255", "#2B0071", "#022394", "#43B54C", "#FAEF44", "#F39E3A", "#EE2939",
                   "#CC99C9", "#9EC1CF", "#9EE09E", "#FDFD97", "#FEB144", "#FF6663")
                   
zion_area <- nps_attains_areas %>% filter(UNIT_CODE == "ZION") %>% group_by(assessmentunitidentifier) %>% summarize() %>% nngeo::st_remove_holes()
shen_lines <- nps_attains_lines %>% filter(UNIT_CODE == "SHEN") %>% group_by(assessmentunitidentifier) %>% summarize()
cong_points <- nps_attains_points %>% filter(UNIT_CODE == "CONG") %>% summarize(assessmentunitidentifier)

romo_area <- nps_attains_areas %>% filter(UNIT_CODE %in% c("ROMO")) %>% group_by(assessmentunitidentifier) %>% summarize() %>% nngeo::st_remove_holes()
romo_lines <- nps_attains_lines %>% filter(UNIT_CODE %in% c("ROMO")) %>% group_by(assessmentunitidentifier) %>% summarize()
romo_points <- nps_attains_points %>% filter(UNIT_CODE %in% c("ROMO"))

line <- ggplot()+
  geom_sf(data = filter(parks, UNIT_CODE == "SHEN"), color = "grey", size = 3, alpha = 0.3) +
  geom_sf(data = shen_lines, aes(color = assessmentunitidentifier), size = 300) +
  scale_color_manual(values=cols) +
  guides(fill = FALSE, color = FALSE, size = FALSE) +
  ggspatial::annotation_scale(location = "br", width_hint = 0.5) +
  theme_void() #+
  #coord_sf(xlim = c(-8767735.715105632, -8752565.094900327), ylim = c(4610175.742603601, 4624269.106648318))

area <- ggplot()+
  geom_sf(data = filter(parks, UNIT_CODE == "ZION"), color = "grey", size = 3, alpha = 0.3) +
  geom_sf(data = zion_area, aes(fill = assessmentunitidentifier), color = "white") +
  #scale_color_viridis_d() +
  scale_fill_manual(values=cols) +
  guides(fill = FALSE, color = FALSE, size = FALSE) +
  annotation_scale(location = "bl", width_hint = 0.5) +
  theme_void()

point <- ggplot()+
  geom_sf(data = filter(parks, UNIT_CODE == "CONG"), color = "grey", size = 3, alpha = 0.3) +
  geom_sf(data = cong_points, aes(color=assessmentunitidentifier), size = 3) +
  scale_fill_manual(values=cols) +
  guides(fill = FALSE, color = FALSE, size = FALSE) +
  ggspatial::annotation_scale(location = "tr", width_hint = 0.5) +
  theme_void()   
  #coord_sf(xlim = c(-8991100.255427620, -9003400.255427629), ylim = c(3994200.255427629, 4017500.255427629))

all <- 
  ggplot()+
  geom_sf(data = filter(parks, UNIT_CODE %in% c("ROMO")), color = "grey", size = 3, alpha = 0.3) +
  geom_sf(data = romo_lines, aes(color = assessmentunitidentifier)) +
  geom_sf(data = romo_points, aes(color = assessmentunitidentifier), size = 3) +
    geom_sf(data = romo_area, aes(fill = assessmentunitidentifier), color = "white") +
  scale_fill_manual(values=cols) +
  scale_color_manual(values=cols) +
  guides(fill = FALSE, color = FALSE, size = FALSE) +
  ggspatial::annotation_scale(location = "br", width_hint = 0.5) +
  theme_void()# +
  #coord_sf(xlim = c(-13888294.255427629, -13871638.63321514), ylim = c(6114044.786919925,6134637.724682183))
#124, 47, 48
ggpubr::ggarrange(point, line, area, all)
```

How many parks have impairments?
```{r}
# how many with impairments?
count <- final_dataset_park %>% filter(ircategory %in% c("5A","5","4C","4B", "4A")) %>%
  distinct(UNIT_CODE) %>% nrow()

total <- n_distinct(parks$UNIT_CODE)# %>% nrow()

# how many with impairments on the 303d list?
final_dataset_park %>% filter(ircategory %in% c("5A","5")) %>%
  distinct(UNIT_CODE, .keep_all = TRUE) #%>% nrow()

park_pie <- tibble(for_pie = c("Impaired", "No Impairments"),
                  count = c(count, total - count)) %>%
  mutate(for_pie = factor(x = for_pie, levels = for_pie)) %>% 
  mutate(prop = count/sum(count)) %>%  
  mutate(ypos = cumsum(prop) - 0.5*prop) %>%
  mutate(legend = paste0(for_pie, " (", scales::percent(prop), ")"))

ggplot(data=park_pie, aes(x="", y=count, fill=legend)) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  scale_fill_manual(values = c("#DC851E", "lightgrey")) + 
  guides(fill=guide_legend(title = "Park Status")) +
  theme_void() + # remove background, grid, numeric label
  theme(text = element_text(size = 20)) 

# By NPCA Region:
offices <- unique(final_dataset_park$office)
plots <- vector("list", length = length(offices))

for(i in 1:length((offices))){
  
  count <- final_dataset_park %>% 
  dplyr::filter(office == offices[i]) %>%
  dplyr::filter(ircategory %in% c("5A","5","4C","4B", "4A")) %>%
  distinct(UNIT_CODE) %>% nrow()
total <- dplyr::filter(parks, office == offices[i]) %>%
  distinct(UNIT_CODE) %>% nrow()

park_pie <- tibble(for_pie = c("Impaired", "No Impairments"),
                  count = c(count, total - count)) %>%
  mutate(for_pie = factor(x = for_pie, levels = for_pie)) %>% 
  mutate(prop = count/sum(count)) %>%  
  mutate(ypos = cumsum(prop) - 0.5*prop) %>%
  mutate(legend = paste0(for_pie, " (", scales::percent(prop), ")"))

plots[[i]] <- ggplot(data=park_pie, aes(x="", y=count, fill=legend)) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  scale_fill_manual(values = c("#DC851E", "lightgrey")) + 
  guides(fill=guide_legend(title = paste0(offices[i], " Region Parks"))) +
  theme_void() + # remove background, grid, numeric label
  theme(text = element_text(size = 20)) 
  
}

ggarrange(plots[[1]], plots[[2]], plots[[3]], plots[[4]],
          plots[[5]], plots[[6]], plots[[7]], plots[[8]],
          plots[[9]], plots[[10]], plots[[11]], 
          nrow = 3)
```


How many assessment units in parks are impaired, good, or unknown?
```{r}
nps_aus <- final_dataset_park %>% #all_nps_aus %>%
  distinct(assessmentunitidentifier, .keep_all = TRUE) %>%
  mutate(for_pie = case_when(ircategory %in% c("5A","5","4C","4B", "4A") ~ "Impaired",
                             ircategory == "3" ~ "Unknown",
                             ircategory %in% c("1","2") ~ "Good"))  %>%
  group_by(for_pie) %>%
  summarize(count=n()) %>%
  ungroup() %>%
  mutate(for_pie = factor(x = for_pie, levels = for_pie)) %>% 
  mutate(prop = count/sum(count)) %>%  
  mutate(ypos = cumsum(prop) - 0.5*prop) %>%
  mutate(legend = paste0(for_pie, " (", scales::percent(prop), ")"))

ggplot(data=nps_aus, aes(x="", y=count, fill=legend)) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  scale_fill_manual(values = c("#059FA4", "#DC851E", "#A1A522")) + 
  guides(fill=guide_legend(title = "Assessment Unit Status")) +
  theme_void() + # remove background, grid, numeric label
  theme(text = element_text(size = 20)) 

# By NPCA Region:
offices <- unique(final_dataset_park$office)
plots <- vector("list", length = length(offices))

for(i in 1:length((offices))){
  
  nps_aus_office <- final_dataset_park %>%
    filter(office == offices[i]) %>%
    distinct(assessmentunitidentifier, .keep_all = TRUE) %>%
    mutate(for_pie = case_when(ircategory %in% c("5A","5","4C","4B", "4A") ~ "Impaired",
                               ircategory == "3" ~ "Unknown",
                               ircategory %in% c("1","2") ~ "Good"))  %>%
    group_by(for_pie) %>%
    summarize(count = n()) %>%
    ungroup() %>%
    mutate(for_pie = factor(x = for_pie, levels = for_pie)) %>% 
    mutate(prop = count/sum(count)) %>%  
    mutate(ypos = cumsum(prop) - 0.5*prop) %>%
    mutate(legend = paste0(for_pie, " (", scales::percent(prop), ")"))
  
  plots[[i]] <- ggplot(data=nps_aus_office, aes(x="", y=count, fill=legend)) +
    geom_bar(stat="identity", width=1, color="white") +
    coord_polar("y", start=0) +
    scale_fill_manual(values = c("#059FA4", "#DC851E", "#A1A522")) +
    guides(fill=guide_legend(title = paste0(offices[i], " Region"))) +
    theme_void() + # remove background, grid, numeric label
    theme(text = element_text(size = 20)) 
  
}

plots[[1]]
plots[[2]]
plots[[3]]
plots[[4]]
plots[[5]]
plots[[6]]
plots[[7]]
plots[[8]]
plots[[9]]
plots[[10]]
plots[[11]]

ggarrange(plots[[1]], plots[[2]], plots[[3]], plots[[4]],
          plots[[5]], plots[[6]], plots[[7]], plots[[8]],
          plots[[9]], plots[[10]], plots[[11]], 
          nrow = 3)
```

What impairments are the most common across park units?
```{r}
top_impairments <- final_dataset_park %>% 
  dplyr::filter(parametercategorycode %in% c("5A","5","4C","4B", "4A")) %>%
  distinct(UNIT_CODE, parametergroupname) %>%
  #mutate(parametergroupname = ifelse(parametergroupname %in% c("ORGANIC ENRICHMENT/OXYGEN DEPLETION", "NUTRIENTS"), "ORGANIC # ENRICHMENT/OXYGEN DEPLETION/NUTRIENTS", parametergroupname)) %>%
  group_by(parametergroupname) %>%
  summarize(count = n())
```

```{r}
top_npca_impairments <- final_dataset_park %>%
  dplyr::filter(parametercategorycode %in% c("5A","5","4C","4B", "4A")) %>%
  distinct(UNIT_CODE, parametergroupname, office) %>%
  group_by(office, parametergroupname) %>%
  summarize(count = n()) %>%
  slice_max(order_by=count, n = 1)
```

```{r}
state_mapper <- full_usa %>%
  usa_mapper()
  
parks_mapper <- parks %>%
  sf::st_centroid() %>%
  st_join(st_transform(tigris::states(), 3857)) %>%
  distinct(UNIT_CODE, .keep_all = TRUE) %>%
  usa_mapper()

pathogens <- final_dataset_park %>%
  dplyr::filter(parametercategorycode %in% c("5A","5","4C","4B", "4A")) %>% 
  dplyr::filter(parametergroupname == "PATHOGENS") %>%
  distinct(UNIT_CODE, .keep_all =TRUE)

pathogen_mapper <- parks %>%
  dplyr::filter(UNIT_CODE %in% pathogens$UNIT_CODE) %>%
  sf::st_centroid() %>%
  st_join(st_transform(tigris::states(), 3857)) %>%
  usa_mapper()


# for(i in 1:nrow(pathogen_mapper)){
# pathogen_mapper$lon[i] = pathogen_mapper$geometry[i][[1]][1]
# pathogen_mapper$lat[i] = pathogen_mapper$geometry[i][[1]][2]
# 
# }
# 
# pathogen_mapper <- usmap::usmap_transform(pathogen_mapper)
# 
# plot_usmap(fill = "yellow", alpha = 0.25) +
  # ggrepel::geom_label_repel(data = cities_t,
  #            aes(x = x, y = y, label = most_populous_city),
  #            size = 3, alpha = 0.8,
  #            label.r = unit(0.5, "lines"), label.size = 0.5,
  #            segment.color = "red", segment.size = 1,
  #            seed = 1002) +
  # geom_point(data = pathogen_mapper,
  #            aes(x = x, y = y),
  #            color = "purple", alpha = 0.5) +
  # scale_size_continuous(range = c(1, 16),
  #                       label = scales::comma) #+
  # labs(title = "Most Populous City in Each US State",
  #      subtitle = "Source: US Census 2010",
  #      size = "City Population") +
  # theme(legend.position = "right")

ggplot() +
  theme_void() +
  #geom_sf(data = county_map, size = 0.1) +
  geom_sf(data = states, fill = NA) +
  geom_sf(data = parks_mapper, color = "lightgrey") + 
  geom_sf(data = pathogen_mapper, color = "#DC851E") 
```


Which parks have antidegradation protections?

```{r}
state_mapper <- full_usa %>%
  usa_mapper()
  
parks_mapper <- parks %>%
  sf::st_centroid() %>%
  st_join(st_transform(tigris::states(), 3857)) %>%
  distinct(UNIT_CODE, .keep_all = TRUE) %>%
  usa_mapper()

orws <- readRDS('data/parks_with_orw.RDS') %>%
  filter(!is.na(orw_id)) %>%
  group_by(unit_code) %>%
  summarize(count = n())

orws_mapper <- parks %>%
  dplyr::filter(UNIT_CODE %in% orws$unit_code) %>%
  sf::st_centroid() %>%
  st_join(st_transform(tigris::states(), 3857)) %>%
  usa_mapper()

ggplot() +
  theme_void() +
  #geom_sf(data = county_map, size = 0.1) +
  geom_sf(data = state_mapper, fill = NA) +
  geom_sf(data = parks_mapper, color = "lightgrey") +
  geom_sf(data = orws_mapper, color = "#059FA4") 
```

